version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: batch_mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=job_repo
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./batch_mysql:/var/lib/mysql